/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module apb_master(pclk, preset_n, transfer, prdata_i, pready_i, psel_o, penable_o, paddr_o, pwrite_o, pwdata_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire apb_state_access;
  wire apb_state_setup;
  wire nxt_pwrite;
  wire [7:0] nxt_rdata;
  output [7:0] paddr_o;
  input pclk;
  output penable_o;
  input [7:0] prdata_i;
  input pready_i;
  input preset_n;
  output psel_o;
  output [7:0] pwdata_o;
  output pwrite_o;
  wire pwrite_q;
  wire [7:0] rdata_q;
  wire [2:0] state_q;
  input [1:0] transfer;
  sky130_fd_sc_hd__clkinv_1 _072_ (
    .A(_067_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _073_ (
    .A(_048_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _074_ (
    .A(_068_),
    .B(_048_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o21ai_0 _075_ (
    .A1(_027_),
    .A2(_070_),
    .B1(_029_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__or2_0 _076_ (
    .A(_068_),
    .B(_069_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a21o_1 _077_ (
    .A1(_068_),
    .A2(_028_),
    .B1(_069_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_0 _078_ (
    .A(_067_),
    .B(_070_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(_058_),
    .A1(_071_),
    .S(_024_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand3b_1 _080_ (
    .A_N(_058_),
    .B(_048_),
    .C(_068_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(_040_),
    .A1(_059_),
    .S(_030_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _082_ (
    .A0(_041_),
    .A1(_060_),
    .S(_030_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(_042_),
    .A1(_061_),
    .S(_030_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(_043_),
    .A1(_062_),
    .S(_030_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _085_ (
    .A0(_044_),
    .A1(_063_),
    .S(_030_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _086_ (
    .A0(_045_),
    .A1(_064_),
    .S(_030_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _087_ (
    .A0(_046_),
    .A1(_065_),
    .S(_030_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _088_ (
    .A0(_047_),
    .A1(_066_),
    .S(_030_),
    .X(_039_)
  );
  sky130_fd_sc_hd__and2_0 _089_ (
    .A(_068_),
    .B(_059_),
    .X(_050_)
  );
  sky130_fd_sc_hd__and2_0 _090_ (
    .A(_068_),
    .B(_060_),
    .X(_051_)
  );
  sky130_fd_sc_hd__and2_0 _091_ (
    .A(_068_),
    .B(_061_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and2_0 _092_ (
    .A(_068_),
    .B(_062_),
    .X(_053_)
  );
  sky130_fd_sc_hd__and2_0 _093_ (
    .A(_068_),
    .B(_063_),
    .X(_054_)
  );
  sky130_fd_sc_hd__and2_0 _094_ (
    .A(_068_),
    .B(_064_),
    .X(_055_)
  );
  sky130_fd_sc_hd__and2_0 _095_ (
    .A(_068_),
    .B(_065_),
    .X(_056_)
  );
  sky130_fd_sc_hd__and2_0 _096_ (
    .A(_068_),
    .B(_066_),
    .X(_057_)
  );
  sky130_fd_sc_hd__dfstp_2 _097_ (
    .CLK(pclk),
    .D(_001_),
    .Q(state_q[0]),
    .SET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(pclk),
    .D(_002_),
    .Q(state_q[1]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(pclk),
    .D(_000_),
    .Q(state_q[2]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(pclk),
    .D(nxt_rdata[0]),
    .Q(rdata_q[0]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(pclk),
    .D(nxt_rdata[1]),
    .Q(rdata_q[1]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(pclk),
    .D(nxt_rdata[2]),
    .Q(rdata_q[2]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(pclk),
    .D(nxt_rdata[3]),
    .Q(rdata_q[3]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(pclk),
    .D(nxt_rdata[4]),
    .Q(rdata_q[4]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(pclk),
    .D(nxt_rdata[5]),
    .Q(rdata_q[5]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(pclk),
    .D(nxt_rdata[6]),
    .Q(rdata_q[6]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(pclk),
    .D(nxt_rdata[7]),
    .Q(rdata_q[7]),
    .RESET_B(preset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(pclk),
    .D(nxt_pwrite),
    .Q(pwrite_q),
    .RESET_B(preset_n)
  );
  assign apb_state_access = state_q[1];
  assign apb_state_setup = state_q[2];
  assign paddr_o = { state_q[1], 1'h0, state_q[1], 1'h0, state_q[1], 1'h0, state_q[1], state_q[1] };
  assign penable_o = state_q[1];
  assign pwrite_o = pwrite_q;
  assign _067_ = state_q[0];
  assign _068_ = state_q[1];
  assign _070_ = transfer[0];
  assign _001_ = _025_;
  assign _048_ = pready_i;
  assign _069_ = state_q[2];
  assign _002_ = _026_;
  assign _058_ = pwrite_q;
  assign _071_ = transfer[1];
  assign nxt_pwrite = _031_;
  assign _040_ = prdata_i[0];
  assign _059_ = rdata_q[0];
  assign nxt_rdata[0] = _032_;
  assign _041_ = prdata_i[1];
  assign _060_ = rdata_q[1];
  assign nxt_rdata[1] = _033_;
  assign _042_ = prdata_i[2];
  assign _061_ = rdata_q[2];
  assign nxt_rdata[2] = _034_;
  assign _043_ = prdata_i[3];
  assign _062_ = rdata_q[3];
  assign nxt_rdata[3] = _035_;
  assign _044_ = prdata_i[4];
  assign _063_ = rdata_q[4];
  assign nxt_rdata[4] = _036_;
  assign _045_ = prdata_i[5];
  assign _064_ = rdata_q[5];
  assign nxt_rdata[5] = _037_;
  assign _046_ = prdata_i[6];
  assign _065_ = rdata_q[6];
  assign nxt_rdata[6] = _038_;
  assign _047_ = prdata_i[7];
  assign _066_ = rdata_q[7];
  assign nxt_rdata[7] = _039_;
  assign _000_ = _024_;
  assign psel_o = _049_;
  assign pwdata_o[0] = _050_;
  assign pwdata_o[1] = _051_;
  assign pwdata_o[2] = _052_;
  assign pwdata_o[3] = _053_;
  assign pwdata_o[4] = _054_;
  assign pwdata_o[5] = _055_;
  assign pwdata_o[6] = _056_;
  assign pwdata_o[7] = _057_;
endmodule
